hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/hucre.o -c ./src/hucre.cpp
	g++ -I ./include/ -o ./lib/doku.o -c ./src/doku.cpp
	g++ -I ./include/ -o ./lib/queue.o -c ./src/queue.cpp
	g++ -I ./include/ -o ./lib/radix.o -c ./src/radix.cpp
	g++ -I ./include/ -o ./lib/bst.o -c ./src/bst.cpp
	g++ -I ./include/ -o ./lib/bstNode.o -c ./src/bstNode.cpp
	g++ -I ./include/ -o ./lib/organ.o -c ./src/organ.cpp
	g++ -I ./include/ -o ./lib/sistem.o -c ./src/sistem.cpp
	g++ -I ./include/ -o ./lib/organizma.o -c ./src/organizma.cpp
	g++ -I ./include/ -o ./lib/kontrol.o -c ./src/kontrol.cpp
	g++ -I ./include/ -o ./lib/print.o -c ./src/print.cpp
	g++ -I ./include/ -o ./lib/mutasyon.o -c ./src/mutasyon.cpp
	g++ -I ./include/ -o ./bin/test ./lib/hucre.o ./lib/doku.o ./lib/queue.o ./lib/radix.o ./lib/bst.o ./lib/bstNode.o ./lib/organ.o ./lib/sistem.o ./lib/organizma.o ./lib/kontrol.o ./lib/print.o ./lib/mutasyon.o  ./src/test.cpp
	
calistir:
	./bin/test